<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxrwzlj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxrwzlj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYxrwzlj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYxrwzlj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYxrwzlj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Yxrwzlj',
    'container.build_id' => '44b27061',
    'container.build_time' => 1536658119,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxrwzlj');
